# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: KoyuMain

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/honjo-s3-access
  S3_BUCKET: ${{ secrets.S3_BUCKET }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: check variables
      run: |
        echo $AWS_ROLE_ARN
        echo ${{ env.S3_BUCKET }}
    - uses: actions/checkout@v4
    - name: Configure AWS credentials from IAM Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install sphinx pydata_sphinx_theme
    - name: Generate reStructuredText files
      run: sphinx-apidoc -f -o sphinx/source src
    - name: Generate HTML files
      run: |
        cd sphinx
        make html
    - name: Sync html to s3
      run: |
        aws s3 sync sphinx/build/html s3://${{ env.S3_BUCKET }}/docs --delete --quiet
